"""empty message

Revision ID: 424f3186a6f4
Revises: 963f0e62b6b9
Create Date: 2025-03-22 02:25:39.861175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424f3186a6f4'
down_revision: Union[str, None] = '963f0e62b6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_history', sa.Column('cost', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_history', 'cost')
    # ### end Alembic commands ###
