"""empty message

Revision ID: 59938e327a05
Revises: f610a3a52e3e
Create Date: 2025-03-14 21:57:59.823772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59938e327a05'
down_revision: Union[str, None] = 'f610a3a52e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_history', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(op.f('fk__orders_history__user_id__users'), 'orders_history', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.drop_constraint(op.f('fk__orders_history__user_id__users'), 'orders_history', type_='foreignkey')
    op.drop_column('orders_history', 'user_id')
    # ### end Alembic commands ###
