"""empty message

Revision ID: 7d58e9d1fc3e
Revises: 8b5d2b997b00
Create Date: 2025-03-01 04:33:46.716015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d58e9d1fc3e'
down_revision: Union[str, None] = '8b5d2b997b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
