"""empty message

Revision ID: 963f0e62b6b9
Revises: 0c9b15a369ba
Create Date: 2025-03-17 19:40:20.510545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963f0e62b6b9'
down_revision: Union[str, None] = '0c9b15a369ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'weight',
               existing_type=sa.TEXT(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
