"""empty message

Revision ID: b7137be20868
Revises: 424f3186a6f4
Create Date: 2025-03-29 02:18:36.740983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7137be20868'
down_revision: Union[str, None] = '424f3186a6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_history', sa.Column('table_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_history', 'table_id')
    # ### end Alembic commands ###
