"""empty message

Revision ID: f610a3a52e3e
Revises: ff1ac13398a4
Create Date: 2025-03-14 21:27:51.156371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f610a3a52e3e'
down_revision: Union[str, None] = 'ff1ac13398a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dishes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__orders_history'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('overallRating', sa.INTEGER(), nullable=True),
    sa.Column('aiRating', sa.INTEGER(), nullable=True),
    sa.Column('atmosphereRating', sa.INTEGER(), nullable=True),
    sa.Column('staffRating', sa.INTEGER(), nullable=True),
    sa.Column('foodRating', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('recommend', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__reviews__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('orders_history')
    # ### end Alembic commands ###
