"""empty message

Revision ID: ff1ac13398a4
Revises: 7d58e9d1fc3e
Create Date: 2025-03-01 04:40:22.267511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1ac13398a4'
down_revision: Union[str, None] = '7d58e9d1fc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('all_ingredients', sa.TEXT(), nullable=True),
    sa.Column('main_ingredients', sa.TEXT(), nullable=True),
    sa.Column('img_link', sa.TEXT(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('cuisine', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__dishes'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('role', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('dishes')
    # ### end Alembic commands ###
