services:
  database:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}
    command: postgres -p ${DATABASE_PORT}
    volumes:
      - ./backend/src/:/data
    networks:
      - internal-net
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

    # frontend:
    #   build:
    #     context: ./frontend
    #     dockerfile: Dockerfile
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./frontend:/app
    #     - /app/node_modules
    #   environment:
    #     - CHOKIDAR_USEPOLLING=true
      # networks:
      #   - app-network
      # depends_on:
      #   - backend
  # cache:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - '${REDIS_PORT}:{REDIS_PORT}'
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   command: 
  #     - redis-server
  #     - --save 20 1
  #     - --loglevel warning
  #     - --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - cache:/data
  # rabbitmq:
  #   image: rabbitmq:4-management
  #   hostname: rabbitmq
  #   restart: always
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  #     - RABBITMQ_PORT=${RABBITMQ_PORT}
  #   ports:
  #     - 15672:15672
  #   networks:
  #     - internal-net

networks:
  internal-net: