const API_BASE_URL = 'http://127.0.0.1:8080';
const ACCESS_API_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJwYXNzd29yZCI6InhkVlZEd1h4Nkg0VU53ZG8iLCJleHAiOjYxNzQwOTQxMTYzfQ.pocs5NFdYMntyB2pamzJpxyRL10f4IXgUx-vLBmXxHc";
const AUTH_HEADER_NAME = "X-Auth-Token";
const USER_ID_HEADER_NAME = "X-UID";