cafe: 
  name: "Neuro"
  tg_link: "https://t.me/neurocafebot"
  email: "info@cafe-neuro.ru"
  phone: "+7 (999) 999-99-99"
  longitude: 91.422759
  latitude: 53.714688
  address: "ул. Пушкина, д. Колотушкина"
  desc: "Лучшее кафе!"

staff:
  - id: 1
    name: "Красивый Крабс"
    status: "Шеф-повар"
    experience_years: 10
    achievements: "Повар мира 2025, Главный повар мира 2024"
    photo_link: "https://storage.yandexcloud.net/memory-minder-images/staff/image.jpg"

  - id: 2
    name: "Прекрасный Боб"
    status: "Су-шеф"
    experience_years: 12
    achievements: "Су-Повар мира 2025, Главный су-повар мира 2024"
    photo_link: "https://storage.yandexcloud.net/memory-minder-images/staff/image-4.jpg"

  - id: 3
    name: "Лейла Кулинарова"
    status: "Повар-кондитер"
    experience_years: 8
    achievements: "Лучший повар вегетарианской кухни 2023, Награда за инновации в кулинарии 2024"
    photo_link: "https://storage.yandexcloud.net/memory-minder-images/staff/image-1.jpg"

  - id: 4
    name: "Анна Гастрономова"
    status: "Консультант по питанию"
    experience_years: 9
    achievements: "Эксперт в области здорового питания 2025, Лауреат премии за лучший кулинарный блог 2024"
    photo_link: "https://storage.yandexcloud.net/memory-minder-images/staff/image-3.jpg"

  - id: 5
    name: "Иван Степанов"
    status: "Кулинарный блогер"
    experience_years: 5
    achievements: "Лучший кулинарный блогер 2024, Награда за лучший видеоблог о еде 2025"
    photo_link: "https://storage.yandexcloud.net/memory-minder-images/staff/image-2.jpg"

interior:
  - id: 1
    img_link: https://storage.yandexcloud.net/memory-minder-images/interior/cafe-1.jpg
  
  - id: 2
    img_link: https://storage.yandexcloud.net/memory-minder-images/interior/cafe-3.jpg
  
  - id: 3
    img_link: https://storage.yandexcloud.net/memory-minder-images/interior/cafe-garderob.jpg
  
  - id: 4
    img_link: https://storage.yandexcloud.net/memory-minder-images/interior/cafe-garderod-2.jpg
  
tables:
  - id: 1
    x: 9
    y: 31
    seats_count: 4

  - id: 2
    x: 9
    y: 9
    seats_count: 4

  - id: 3
    x: 26
    y: 9
    seats_count: 4

  - id: 4
    x: 47
    y: 10
    seats_count: 4

  - id: 5
    x: 47
    y: 35
    seats_count: 4

  - id: 6
    x: 47
    y: 61
    seats_count: 4

  - id: 7
    x: 47
    y: 87
    seats_count: 4

  - id: 8
    x: 65
    y: 77
    seats_count: 4

  - id: 9
    x: 65
    y: 50
    seats_count: 4

  - id: 10
    x: 65
    y: 23
    seats_count: 4

  - id: 11
    x: 87
    y: 11
    seats_count: 6

  - id: 12
    x: 87
    y: 36
    seats_count: 6

  - id: 13
    x: 87
    y: 62
    seats_count: 6

  - id: 14
    x: 87
    y: 88
    seats_count: 6

  - id: 15
    x: 12
    y: 51
    seats_count: 1

  - id: 16
    x: 12
    y: 55
    seats_count: 1

  - id: 17
    x: 12
    y: 59
    seats_count: 1

  - id: 18
    x: 12
    y: 65
    seats_count: 1

  - id: 19
    x: 12
    y: 69
    seats_count: 1

  - id: 20
    x: 12
    y: 73
    seats_count: 1

  - id: 21
    x: 12
    y: 80
    seats_count: 1

  - id: 22
    x: 12
    y: 84
    seats_count: 1

  - id: 23
    x: 12
    y: 88
    seats_count: 1